### PR TITLE
Glog 32 theme changer implementation

### PR DESCRIPTION
**Pull request by srayce1**

### CODE REVIEW

**Comment by Jhavaa** [comment]
The package-lock file has a few new packages added. Did you run an NPM install on stuff for this project? I ask to make sure these packages are necessary, since we've been able to run the app on main with no issues.

**Review by Jhavaa — CHANGES_REQUESTED** [review]
I'd recommend removing imports in pages that don't need it. For example, _app.js has an import for themeChange which isn't used. Look through what you've edited and make sure we are using your imports. (we can always add them back later)

**Comment by Jhavaa** [comment]
I think the way you are using theme changer is great. I do have some changes that I would like to see before we push:

1.    I think the "Default" should be removed, since it can be confusing. when switching between themes. Default value is determined by the user's browser preference. To access that preference, follow this [article](https://flaviocopes.com/javascript-detect-dark-mode/). I believe that this could help us get rid of "default" and just automatically select the value based on preference, if this is the users first visit (AKA theme isn't stored in local storage). This [article](https://reactjs.org/docs/forms.html#the-select-tag.) shows you how react allows you to pre-select an option.
     - This won't be an easy fix, so take your time and ask for help if you wanna work on this together.

3. I got a few errors because of invalid property names. Make sure to correct that, by following the advised corrected syntax. It still works, but we don't want to clog console with all these unnecessary errors.

**Review by Jhavaa — APPROVED** [review]
Applied fix I outlined. Decided to change my approach and choose to select theme through a dropdown menu of buttons. This way, the user can select a theme and not be confused by "default" as an option.

Also I accidentally removed the feature slider in a previous feature merge, so I'm adding it back here lol.

**Review by Chris-Boho — APPROVED** [review]
A+ from me!

**Pull request merged**
