### PR TITLE
Glog 4 create home page queries for carousel

### PR DESCRIPTION
**Pull request by Chris-Boho**
Just pushing this, so you guys can see. I wouldn't consider this finished cause the slider looks messed up in full screen. (Too big it feels like). 

I dont like how I have to copy and paste the filters + query + response each time for a Slider. I tried to get a for loop to work for it (which is commented out). There were two problems. 

I tried to replicate gameMasterList but I couldnt get the objects to show in the slider (probably a simple fix i just dont know it). 

The second issue is that it takes MUCH longer to refresh/load the page with the FOR loop and im not sure why. It already normally takes a bit to load cause it loads things twice, but with the FOR loop it takes longer. This is part of the reason I just didnt try to get the for loop to work because I dont think the increased load times is worth it.

### CODE REVIEW

**Comment by Chris-Boho** [comment]
oh god why so many conflicts

**Comment by Jhavaa** [comment]
oops lol didn't mean to close

**Comment by Jhavaa** [comment]
Make sure to resolve these conflicts locally by merging main to your branch.

On another note, just a reminder to check out [static rendering](https://nextjs.org/docs/basic-features/data-fetching/get-static-props). This could benefit the home page, since we are always going to have the same set of carousals/game info. It's more noticeable if you build the project and then run the build, but still worth looking into and considering.

**Review by srayce1 — APPROVED** [review]

**Review by Jhavaa — APPROVED** [review]
I made some code refactoring stuff. Didn't change the logic, cause it was working exactly as intended 👍

**Pull request merged**
